const mongoose = require("mongoose");
const Movie = require("./models/Movie");

const movies = [
  {
    title: "Interstellar",
    description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    genre: "Sci-Fi",
    duration: "2h 49m",
    rating: 8.6,
    image: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    showTimes: ["10:00 AM", "2:00 PM", "7:00 PM"],
  },
  {
    title: "The Dark Knight",
    description: "Batman raises the stakes in his war on crime with the help of Lt. Jim Gordon and DA Harvey Dent.",
    genre: "Action",
    duration: "2h 32m",
    rating: 9.0,
    image: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    showTimes: ["11:00 AM", "3:00 PM", "8:00 PM"],
  },
  {
    title: "Inception",
    description: "A thief who steals corporate secrets through dream-sharing technology is given a task to plant an idea.",
    genre: "Thriller",
    duration: "2h 28m",
    rating: 8.8,
    image: "https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
    showTimes: ["9:00 AM", "1:00 PM", "6:00 PM"],
  },
  {
    title: "The Avengers",
    description: "Earth's mightiest heroes must come together to stop Loki and his alien army from enslaving humanity.",
    genre: "Action",
    duration: "2h 23m",
    rating: 8.0,
    image: "https://image.tmdb.org/t/p/w500/RYMX2wcKCBAr24UyPD7KE3Xe7my.jpg",
    showTimes: ["10:30 AM", "2:30 PM", "7:30 PM"],
  },
  {
    title: "Parasite",
    description: "Greed and class discrimination threaten the newly formed symbiotic relationship between two families.",
    genre: "Drama",
    duration: "2h 12m",
    rating: 8.5,
    image: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    showTimes: ["12:00 PM", "4:00 PM", "9:00 PM"],
  },
  {
    title: "Dune",
    description: "A noble family becomes embroiled in a war for control over the galaxy's most valuable asset.",
    genre: "Sci-Fi",
    duration: "2h 35m",
    rating: 8.0,
    image: "https://image.tmdb.org/t/p/w500/d5NXSklpcvkeyd9ho3wBd9pbXjH.jpg",
    showTimes: ["11:30 AM", "3:30 PM", "8:30 PM"],
  },
  {
    title: "Oppenheimer",
    description: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.",
    genre: "Drama",
    duration: "3h 0m",
    rating: 8.4,
    image: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGClnucpEm5.jpg",
    showTimes: ["10:15 AM", "2:45 PM", "7:15 PM"],
  },
  {
    title: "Barbie",
    description: "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land.",
    genre: "Comedy",
    duration: "1h 54m",
    rating: 7.9,
    image: "https://image.tmdb.org/t/p/w500/NNZ6pIII03nMgnq0m7nLrBkT61I.jpg",
    showTimes: ["11:00 AM", "3:00 PM", "6:30 PM"],
  },
  {
    title: "Top Gun: Maverick",
    description: "After thirty years, Maverick is drawn back into the cockpit to confront his past while training a new generation.",
    genre: "Action",
    duration: "2h 11m",
    rating: 8.3,
    image: "https://image.tmdb.org/t/p/w500/Kzg0vFfBP9NzTzdCpyqsVJoECJL.jpg",
    showTimes: ["11:30 AM", "4:00 PM", "8:30 PM"],
  },
  {
    title: "Avatar: The Way of Water",
    description: "Jake Sully and Neytiri have formed a family and are doing everything to stay together, but must leave their home.",
    genre: "Sci-Fi",
    duration: "3h 12m",
    rating: 7.8,
    image: "https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
    showTimes: ["10:00 AM", "3:00 PM", "8:00 PM"],
  },
  {
    title: "Killers of the Flower Moon",
    description: "An FBI agent infiltrates an Osage Nation plot to steal their oil fortune. Based on true events.",
    genre: "Drama",
    duration: "3h 26m",
    rating: 8.1,
    image: "https://image.tmdb.org/t/p/w500/dv1r3ELr7v1Gmk4ZqxAaBhr7YWI.jpg",
    showTimes: ["12:30 PM", "4:00 PM", "8:00 PM"],
  },
  {
    title: "Past Lives",
    description: "A woman reconnects with her first love years later, exploring their relationship across different timelines.",
    genre: "Drama",
    duration: "1h 54m",
    rating: 8.0,
    image: "https://image.tmdb.org/t/p/w500/8HPdrtMWM2r7d0EeJQW9B8BdSwb.jpg",
    showTimes: ["11:00 AM", "3:30 PM", "7:00 PM"],
  },
  {
    title: "Mission: Impossible - Dead Reckoning",
    description: "Ethan Hunt and his IMF team must race against time before a rogue AI capability falls into the wrong hands.",
    genre: "Action",
    duration: "2h 44m",
    rating: 7.7,
    image: "https://image.tmdb.org/t/p/w500/NNZ6pIII03nMgnq0m7nlC9wAGEV.jpg",
    showTimes: ["10:30 AM", "3:30 PM", "7:45 PM"],
  },
  {
    title: "The Shawshank Redemption",
    description: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    genre: "Drama",
    duration: "2h 22m",
    rating: 9.3,
    image: "https://image.tmdb.org/t/p/w500/lyQCXzENkn5B2yBKmp7MxR0iO50.jpg",
    showTimes: ["9:00 AM", "2:00 PM", "6:30 PM"],
  },
  {
    title: "Pulp Fiction",
    description: "Multiple storylines intertwine with hitmen, gangsters, boxers, and gangsters' wives in 1990s Los Angeles.",
    genre: "Crime",
    duration: "2h 34m",
    rating: 8.9,
    image: "https://image.tmdb.org/t/p/w500/d5iIlW_JdzzoMALc5rm_K964fY1.jpg",
    showTimes: ["10:00 AM", "2:30 PM", "7:30 PM"],
  },
  {
    title: "The Matrix",
    description: "A hacker is introduced to the real world and the truth about his reality and his role in the war against its controllers.",
    genre: "Sci-Fi",
    duration: "2h 16m",
    rating: 8.7,
    image: "https://image.tmdb.org/t/p/w500/vhmx4smsW5oluKzVBtFW6Ixw3KL.jpg",
    showTimes: ["9:30 AM", "1:30 PM", "6:00 PM"],
  },
  {
    title: "Forrest Gump",
    description: "The presidencies of Kennedy and Johnson unfold from the perspective of an Alabama man with an IQ of 75.",
    genre: "Drama",
    duration: "2h 22m",
    rating: 8.8,
    image: "https://image.tmdb.org/t/p/w500/weUSwMKWe9uBuFJSTadw0B7rMSV.jpg",
    showTimes: ["11:00 AM", "3:00 PM", "6:45 PM"],
  },
];

mongoose
  .connect("mongodb://localhost:27017/moviebooking")
  .then(async () => {
    await Movie.deleteMany(); // clear old data
    await Movie.insertMany(movies);
    console.log("Movies added to database!");
    process.exit();
  })
  .catch((err) => console.log(err));